name: Deploy Public API

on:
  push:
    branches:
      - master

jobs:
  test-build-deploy:
    name: Test, Build, and Deploy Public API
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }} \
            -t registry.heroku.com/${{ secrets.PUBLIC_API_HEROKU_APP_NAME }}/web .

      # Push Docker image to Heroku Container Registry
      - name: Push Docker Image to Heroku
        run: |
          echo ${HEROKU_API_KEY} | docker login --username=_ --password-stdin registry.heroku.com
          docker push registry.heroku.com/${{ secrets.PUBLIC_API_HEROKU_APP_NAME }}/web

      # Release the app on Heroku
      - name: Release App on Heroku
        run: |
          heroku container:release web --app ${{ secrets.PUBLIC_API_HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
